version: "3.9"

services:
  node:
    image: ghcr.io/web4application/fadaka-node:latest
    container_name: fadaka-node
    ports:
      - "30303:30303"    # P2P
      - "8545:8545"      # JSON-RPC
      - "8546:8546"      # WebSocket
    volumes:
      - ./config.toml:/app/config.toml
      - ./data:/app/data
    restart: unless-stopped

  api:
    image: ghcr.io/web4application/fadaka-api:latest
    container_name: fadaka-api
    ports:
      - "8000:8000"
    depends_on:
      - node
    environment:
      - NODE_RPC_URL=http://node:8545
    restart: unless-stopped

  ui:
    image: ghcr.io/web4application/fadaka-ui:latest   # If you published Streamlit as well
    container_name: fadaka-ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: unless-stopped
