{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fadaka-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.secretName }}
  tls:
  - hosts: [ {{ .Values.ingress.host }} ]
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: fadaka-api
            port:
              number: 8000
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: fadaka-ui
            port:
              number: 8501
{{- end }}
