---
apiVersion: v1
kind: Service
metadata:
  name: fadaka-node
spec:
  selector:
    app: fadaka-node
  ports:
  - name: p2p
    port: 30303
    targetPort: {{ .Values.node.p2pPort }}
  - name: rpc
    port: 8545
    targetPort: {{ .Values.node.rpcPort }}
  - name: ws
    port: 8546
    targetPort: {{ .Values.node.wsPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: fadaka-api
spec:
  selector:
    app: fadaka-api
  ports:
  - port: 8000
    targetPort: {{ .Values.api.port }}
---
{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: fadaka-ui
spec:
  selector:
    app: fadaka-ui
  ports:
  - port: 8501
    targetPort: {{ .Values.ui.port }}
{{- end }}
