name: Build & Push Multi‑Arch Docker Images

on:
  push:
    branches: [main]
    tags: ["v*"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & push (${{ matrix.platform }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Optional second registry (e.g. AWS ECR) – uncomment if needed
      # - name: Log in to Amazon ECR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ secrets.AWS_REGISTRY }}
      #     username: AWS
      #     password: ${{ secrets.AWS_ECR_LOGIN }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/web4application/fadaka:${{ github.sha }}
            ghcr.io/web4application/fadaka:latest
            # ghcr.io/web4application/fadaka:${{ github.ref_name }}  # tag build
          build-args: |
            GIT_COMMIT=${{ github.sha }}

  # Create and push multi‑arch manifest
  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest
        run: |
          docker buildx imagetools create \
            -t ghcr.io/web4application/fadaka:latest \
            ghcr.io/web4application/fadaka@$(docker buildx imagetools inspect ghcr.io/web4application/fadaka:${{ github.sha }} | grep -m1 'Digest:' | awk '{print $2}')
